feat: RecentResults & RecentSearches added in analytics
appbaseio/batteries pull request #250
Opened 2021-02-11 05:45 UTC by anik-ghosh-au7

- Issue Type - Enhancement

- Issue Link - https://www.notion.so/Arc-Dashboard-Add-analytics-views-for-recent-searches-results-e6fe6846ffb349848f11c5d8fe9ee7e1

- Description - Recent Searches and Recent Results components added for analytics view in arc-dashboard

2021-02-11 12:30 UTC, bietkul requested changes
@anik-ghosh-au7 Use Redux to manage state.

2021-02-12 12:27 UTC, anik-ghosh-au7 commented
@bietkul shifted the state management to redux

2021-02-12 13:06 UTC, bietkul requested changes

2021-02-12 13:06 UTC, bietkul commented on components/analytics/utils.js
> +	return [...defaultColumns(), ...(displayReplaySearch ? replaySearch : [])];
@anik-ghosh-au7 Remove the logic based on plans.

2021-02-12 13:06 UTC, bietkul commented on components/analytics/utils.js
> +		{
@anik-ghosh-au7 Return all columns and remove the plan.

2021-02-12 13:06 UTC, bietkul commented on components/analytics/components/RecentSearches.js
> +		const { filters } = this.props;
@anik-ghosh-au7 Error handling is missing. https://github.com/appbaseio/batteries/blob/b6259088c1f8c8d3de9456975c5a43f06cc40434/components/analytics/components/RequestDistribution/index.js#L57

2021-02-12 13:06 UTC, bietkul commented on components/analytics/components/RecentResults.js
> +		const { filters } = this.props;
Error handling https://github.com/appbaseio/batteries/blob/b6259088c1f8c8d3de9456975c5a43f06cc40434/components/analytics/components/RequestDistribution/index.js#L57

2021-02-12 14:45 UTC, anik-ghosh-au7 commented on modules/actions/analytics.js
> +						AppConstants.APP.ANALYTICS.GET_POPULAR_SEARCHES_ERROR,
@bietkul done

2021-02-12 14:48 UTC, bietkul requested changes
@anik-ghosh-au7 Minor changes required

2021-02-12 14:48 UTC, bietkul commented on components/analytics/utils.js
> + * Get the no results seraches
@anik-ghosh-au7 Fix comment

2021-02-12 14:48 UTC, bietkul commented on components/analytics/utils.js
> + * Get the no results seraches
@anik-ghosh-au7 Fix comment

2021-02-12 15:31 UTC, anik-ghosh-au7 commented
demo - https://www.loom.com/share/89fa7e1a46dc455092d5837503ba50a3

2021-02-15 00:28 UTC, merged