fix: optimise initial rendering time in analytics overview
appbaseio/batteries pull request #258
Opened 2021-03-30 21:48 UTC by anik-ghosh-au7

- Issue Type - Bug

- Description - The analytics overview page was making all the requests and rendering all its children components as soon as the component mounts which increases the total load time for the page. Added ids to all the components for conditional rendering for components that are once present in the viewport.

- Please look into the following PR for further reference - appbaseio-confidential/arc-dashboard#327

2021-03-31 14:14 UTC, bietkul requested changes
@anik-ghosh-au7 Move the views associated with advanced analytics endpoint to a single component and render it after summary with a unique id.

2021-03-31 14:14 UTC, bietkul commented on components/analytics/components/Analytics.js
> +	const inViewPort = (id) => {
Put it in util file

2021-03-31 14:14 UTC, bietkul commented on components/analytics/components/Analytics.js
> +				{visibility['summary-component'] && <Summary filterId={filterId} />}
Use the div with id

2021-03-31 14:14 UTC, bietkul commented on components/analytics/components/Analytics.js
>  				</React.Fragment>
Add request logs component at here

2021-04-01 13:42 UTC, anik-ghosh-au7 commented
@bietkul I have done the changes
https://www.loom.com/share/a2d93d7ec3fd4497a0cb5bc11bf3d427

2021-04-02 15:12 UTC, anik-ghosh-au7 commented
@bietkul 

demo updated version - 

https://www.loom.com/share/34ee743493424544a91c236c17f3f7f6

2021-04-05 07:44 UTC, bietkul requested changes

2021-04-05 07:44 UTC, bietkul commented on components/analytics/AdvancedAnalytics.js
> +	onClickViewAll: PropTypes.shape({
@anik-ghosh-au7 Is that prop added by you? If yes then why?

2021-04-05 07:44 UTC, bietkul commented on components/analytics/components/Analytics.js
> +		const initTracker = setTimeout(() => {
@anik-ghosh-au7 Why are you using `setTimeout`?

2021-04-05 07:44 UTC, bietkul commented on components/analytics/components/Analytics.js
> +				clearTimeout(initTracker);
@anik-ghosh-au7 Revisit this too.

2021-04-05 07:44 UTC, bietkul commented on components/analytics/index.js
>  	fetchAppAnalytics: PropTypes.func.isRequired,
@anik-ghosh-au7 Why is it there? Do you not see lint errors?

2021-04-05 07:44 UTC, bietkul commented on components/analytics/index.js
>  		filters: get(state, `$getSelectedFilters.${props.filterId}`),
@anik-ghosh-au7 Where are you using `filters` in this component?

2021-04-05 17:37 UTC, bietkul approved these changes

2021-04-05 18:05 UTC, merged